# Generated by Django 6.0.6 on 2026-07-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route_legs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TripCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("distance_km_snapshot", models.FloatField(help_text="total_distance_km do Trip no momento do cálculo")),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trip", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cost", to="trip.trip")),
            ],
        ),
    ]
